<?php

namespace Apibundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Car
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Car extends EntityRepository
{
}
