<?php

namespace Apibundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Equipment
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Equipment extends EntityRepository
{
}
